server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:file:~/projectcrud
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /db
      settings:
        trace: false
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create-drop
      


    